import java.awt.Image;

import javax.swing.ImageIcon;

public class Building 
{
	String name;
	int cost;
	int cultureBenefit;
	int moneyBenefit;
	int scienceBenefit;
	int happinessBenefit;
	int militaryBenefit;
	static Image monumentimg = new ImageIcon(Unit.class.getResource("MonumentIcon(Civ5).png")).getImage(),
			granaryimg = new ImageIcon(Unit.class.getResource("Granary_(Civ5).png")).getImage(),
			stoneworksimg = new ImageIcon(Unit.class.getResource("Stone_works_(Civ5).png")).getImage(),
			libraryimg = new ImageIcon(Unit.class.getResource("LibraryIcon(Civ5).png")).getImage(),
			circusimg = new ImageIcon(Unit.class.getResource("Circus_(Civ5).png")).getImage(),
			waterMillimg = new ImageIcon(Unit.class.getResource("Water_mill_(Civ5).png")).getImage(),
			wallsimg = new ImageIcon(Unit.class.getResource("Walls_(Civ5).png")).getImage(),
			barracksimg = new ImageIcon(Unit.class.getResource("Barracks_(Civ5).png")).getImage(),
			lighthouseimg = new ImageIcon(Unit.class.getResource("Lighthouse.png")).getImage(),
			templeimg = new ImageIcon(Unit.class.getResource("Temple.png")).getImage(),
			stableimg = new ImageIcon(Unit.class.getResource("Ducal_stable_(Civ5).png")).getImage(),
			courthouseimg = new ImageIcon(Unit.class.getResource("Courthouse.png")).getImage(),
			colloseumimg = new ImageIcon(Unit.class.getResource("Colosseum_(Civ5).png")).getImage(),
			monasteryimg = new ImageIcon(Unit.class.getResource("Monastery_(Civ5).png")).getImage(),
			gardenimg = new ImageIcon(Unit.class.getResource("Garden.png")).getImage(),
			marketimg = new ImageIcon(Unit.class.getResource("Market.png")).getImage(),
			mintimg = new ImageIcon(Unit.class.getResource("Mint.png")).getImage(),
			aqueductimg = new ImageIcon(Unit.class.getResource("Aqueduct.png")).getImage(),
			forgeimg = new ImageIcon(Unit.class.getResource("Forge.png")).getImage(),
			workshopimg = new ImageIcon(Unit.class.getResource("Workshop_(Civ5).png")).getImage(),
			harborimg = new ImageIcon(Unit.class.getResource("Harbor.png")).getImage(),
			universityimg = new ImageIcon(Unit.class.getResource("UniversityIcon(Civ5).png")).getImage(),
			castleimg = new ImageIcon(Unit.class.getResource("Castle.png")).getImage(),
			armoryimg = new ImageIcon(Unit.class.getResource("Armory_(Civ5).png")).getImage(),
			observatoryimg = new ImageIcon(Unit.class.getResource("Observatory_(Civ5).png")).getImage(),
			operaHouseimg = new ImageIcon(Unit.class.getResource("Opera_house_(Civ5).png")).getImage(),
			bankimg = new ImageIcon(Unit.class.getResource("Bank_(Civ5).png")).getImage(),
			theatreimg = new ImageIcon(Unit.class.getResource("Theatre_(Civ5).png")).getImage(),
			seaportimg = new ImageIcon(Unit.class.getResource("Seaport_(Civ5).png")).getImage(),
			windmillimg = new ImageIcon(Unit.class.getResource("Windmill_(Civ5).png")).getImage(),
			museumimg = new ImageIcon(Unit.class.getResource("Museum_(Civ5).png")).getImage(),
			publicSchoolimg = new ImageIcon(Unit.class.getResource("Public_school_(Civ5).png")).getImage(),
			militaryAcademyimg= new ImageIcon(Unit.class.getResource("Military_academy_(Civ5).png")).getImage(),
			arsenalimg = new ImageIcon(Unit.class.getResource("ArsenalIcon(Civ5).png")).getImage(),
			hospitalimg = new ImageIcon(Unit.class.getResource("hospital.png")).getImage(),
			factoryimg = new ImageIcon(Unit.class.getResource("FactoryIcon(Civ5).png")).getImage(),
			stockExchangeimg = new ImageIcon(Unit.class.getResource("Stock_exchange_(Civ5).png")).getImage(),
			militaryBaseimg = new ImageIcon(Unit.class.getResource("Military_Base_(Civ5).png")).getImage(),
			broadcastTowerimg = new ImageIcon(Unit.class.getResource("Broadcast_tower_(Civ5).png")).getImage(),
			hydroPlantimg = new ImageIcon(Unit.class.getResource("Hydro_plant_(Civ5).png")).getImage(),
			researchLabimg = new ImageIcon(Unit.class.getResource("Research_lab_(Civ5).png")).getImage(),
			medicalLabimg = new ImageIcon(Unit.class.getResource("Medical_lab_(Civ5).png")).getImage(),
			stadiumimg = new ImageIcon(Unit.class.getResource("StadiumIcon(Civ5).png")).getImage(),
			solarPlantimg = new ImageIcon(Unit.class.getResource("Solar_plant_(Civ5).png")).getImage(),
			nuclearPlantimg = new ImageIcon(Unit.class.getResource("Nuclear_plant_(Civ5).png")).getImage(),
			spaceshipFactoryimg = new ImageIcon(Unit.class.getResource("Spaceship_factory_(Civ5).png")).getImage(),
			templeOfArtemisimg = new ImageIcon(Unit.class.getResource("Temple_of_Artemis_(Civ5).png")).getImage(),
			stonehengeimg = new ImageIcon(Unit.class.getResource("Stonehenge_(Civ5).png")).getImage(),
			greatLibraryimg = new ImageIcon(Unit.class.getResource("Great_Library_(Civ5).png")).getImage(),
			pyramidsimg = new ImageIcon(Unit.class.getResource("Pyramids_(Civ5).png")).getImage(),
			mausoleumOfHalicarnassusimg = new ImageIcon(Unit.class.getResource("Mausoleum_of_Halicarnassus_(Civ5).png")).getImage(),
			statueOfZeusimg= new ImageIcon(Unit.class.getResource("Statue_of_Zeus_(Civ5).png")).getImage(),
			greatLighthouseimg = new ImageIcon(Unit.class.getResource("Great_Lighthouse_(Civ5).png")).getImage(),
			hangingGardensimg = new ImageIcon(Unit.class.getResource("Hanging_Gardens_(Civ5).png")).getImage(),
			teracottaArmyimg = new ImageIcon(Unit.class.getResource("Terracotta_Army_(Civ5).png")).getImage(),
			oracleimg = new ImageIcon(Unit.class.getResource("Oracle_(Civ5).png")).getImage(),
			petraimg = new ImageIcon(Unit.class.getResource("Petra_(Civ5).png")).getImage(),
			greatWallimg = new ImageIcon(Unit.class.getResource("Great_Wall_(Civ5).png")).getImage(),
			colossusimg = new ImageIcon(Unit.class.getResource("Colossus_(Civ5).png")).getImage(),
			hagiaSophiaimg = new ImageIcon(Unit.class.getResource("Hagia_Sophia_(Civ5).png")).getImage(),
			greatMosqueOfDjenneimg = new ImageIcon(Unit.class.getResource("Great_Mosque_of_Djenne_(Civ5).png")).getImage(),
			borobudurimg = new ImageIcon(Unit.class.getResource("Borobudur_(Civ5).png")).getImage(),
			chichenItzaimg = new ImageIcon(Unit.class.getResource("Chichen_Itza_(Civ5).png")).getImage(),
			machuPicchuimg = new ImageIcon(Unit.class.getResource("Machu_Picchu_(Civ5).png")).getImage(),
			angkorWatimg = new ImageIcon(Unit.class.getResource("Angkor_Wat_(Civ5).png")).getImage(),
			notreDameimg = new ImageIcon(Unit.class.getResource("Notre_Dame_(Civ5).png")).getImage(),
			sistineChapelimg = new ImageIcon(Unit.class.getResource("Sistine_Chapel_(Civ5).png")).getImage(),
			forbiddenPalaceimg = new ImageIcon(Unit.class.getResource("Forbidden_Palace_(Civ5).png")).getImage(),
			leaningTowerOfPisaimg = new ImageIcon(Unit.class.getResource("Leaning_Tower_of_Pisa_(Civ5).png")).getImage(),
			globeTheatreimg = new ImageIcon(Unit.class.getResource("Globe_Theatre_(Civ5).png")).getImage(),
			himejiCastleimg = new ImageIcon(Unit.class.getResource("Himeji_Castle_(Civ5).png")).getImage(),
			porcelainTowerimg = new ImageIcon(Unit.class.getResource("Porcelain_Tower_(Civ5).png")).getImage(),
			tajMahalimg = new ImageIcon(Unit.class.getResource("Taj_Mahal_(Civ5).png")).getImage(),
			uffiziimg = new ImageIcon(Unit.class.getResource("Uffizi_(Civ5).png")).getImage(),
			redFortimg = new ImageIcon(Unit.class.getResource("Red_Fort_(Civ5).png")).getImage(),
			louvreimg = new ImageIcon(Unit.class.getResource("Louvre_(Civ5).png")).getImage(),
			bigBenimg = new ImageIcon(Unit.class.getResource("Big_Ben_(Civ5).png")).getImage(),
			brandenburgGateimg = new ImageIcon(Unit.class.getResource("Brandenburg_Gate_(Civ5).png")).getImage(),
			eiffelTowerimg = new ImageIcon(Unit.class.getResource("Eiffel_Tower_(Civ5).png")).getImage(),
			statueOfLibertyimg = new ImageIcon(Unit.class.getResource("Statue_of_Liberty_(Civ5).png")).getImage(),
			proraimg = new ImageIcon(Unit.class.getResource("Prora_(Civ5).png")).getImage(),
			kremlinimg = new ImageIcon(Unit.class.getResource("Kremlin_(Civ5).png")).getImage(),
			neuschwansteinimg = new ImageIcon(Unit.class.getResource("Neuschwanstein_(Civ5).png")).getImage(),
			cristoRedentorimg = new ImageIcon(Unit.class.getResource("Cristo_Redentor_(Civ5).png")).getImage(),
			pentagonimg = new ImageIcon(Unit.class.getResource("Pentagon_(Civ5).png")).getImage(),
			sydneyOperaHouseimg = new ImageIcon(Unit.class.getResource("Sydney_Opera_House_(Civ5).png")).getImage()
			;
}
